//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "gecko_chain")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub gecko_id: String,
    pub contract: String,
    pub decimals: i32,
    pub blockchain: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::gecko_list::Entity",
        from = "Column::GeckoId",
        to = "super::gecko_list::Column::GeckoId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GeckoList,
}

impl Related<super::gecko_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeckoList.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
