//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "gecko_list")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub gecko_id: String,
    pub symbol: String,
    pub rank: i32,
    pub price: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::gecko_chain::Entity")]
    GeckoChain,
}

impl Related<super::gecko_chain::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeckoChain.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
